db {
    default {
        driver="org.sqlite.JDBC"
        url="jdbc:sqlite:/db/db.sqlite3?foreign_keys=on&journal_mode=WAL&synchronous=NORMAL&busy_timeout=5000"
        user=""
        password=""
        poolInitialSize=1
        poolMaxSize=5
    }
}

scalikejdbc {
    global {
        loggingConnections = false
        loggingSQLAndTime {
            enabled = false
            singleLineMode = true
            logLevel = "DEBUG"
            warningEnabled = true
            warningThresholdMillis = 3000
            warningLogLevel = "WARN"
        }
    }
}
