events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name api.requestbin.localhost;

        location / {
            proxy_pass http://api;

            proxy_set_header Host $http_host;
        }
    }

    #server {
    #    listen 80;
    #    server_name requestbin.localhost;
    #
    #    location / {
    #        proxy_pass http://web;
    #        proxy_set_header Host $http_host;
    #        
    #        proxy_set_header Upgrade $http_upgrade;
    #        proxy_set_header Connection "upgrade";
    #    }
    #}
}