events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;
        server_name api.requestbin.localhost *.api.requestbin.localhost;

        ssl_certificate /etc/nginx/certs/requestbin.localhost.crt;
        ssl_certificate_key /etc/nginx/certs/requestbin.localhost.key;

        location / {
            proxy_pass http://api;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
        }
    }

    server {
        listen 443 ssl;
        server_name requestbin.localhost;
    
        ssl_certificate /etc/nginx/certs/requestbin.localhost.crt;
        ssl_certificate_key /etc/nginx/certs/requestbin.localhost.key;

        location / {
            proxy_pass http://web;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}